### ISSUE TITLE
Error in start php socket

### ISSUE THREAD

**Issue by amin0256** [walkor/phpsocket.io#106]
Hi,
I cant use from this library,
When i start using from web socket ( connect to this web server from a JS file ), this error occurred:
```

Exception 'ArgumentCountError' with message 'Too few arguments to function PHPSocketIO\Engine\Engine::dealWebSocketConnect(), 3 passed and exactly 4 expected'

in /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Engine.php:264

Stack trace:
#0 [internal function]: PHPSocketIO\Engine\Engine->dealWebSocketConnect(NULL, true, Object(PHPSocketIO\Engine\Protocols\Http\Request))
#1 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Engine.php(142): call_user_func(Array, NULL, true, Object(PHPSocketIO\Engine\Protocols\Http\Request))
#2 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Engine.php(133): PHPSocketIO\Engine\Engine->checkRequest(Object(PHPSocketIO\Engine\Protocols\Http\Request), Array)
#3 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Engine.php(261): PHPSocketIO\Engine\Engine->verify(Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response), true, Array)
#4 [internal function]: PHPSocketIO\Engine\Engine->onWebSocketConnect(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response))
#5 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Protocols/WebSocket/RFC6455.php(283): call_user_func_array(Array, Array)
#6 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Protocols/WebSocket.php(84): PHPSocketIO\Engine\Protocols\WebSocket\RFC6455::dealHandshake(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response))
#7 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Protocols/SocketIO.php(38): PHPSocketIO\Engine\Protocols\WebSocket::dealHandshake(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response))
#8 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Connection/TcpConnection.php(444): PHPSocketIO\Engine\Protocols\SocketIO::input('GET /socket.io/...', Object(Workerman\Connection\TcpConnection))
#9 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #78)
#10 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Events/Select.php(286): call_user_func_array(Array, Array)
#11 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(1578): Workerman\Events\Select->loop()
#12 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(966): Workerman\Worker->run()
#13 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(929): Workerman\Worker::forkOneWorker(Object(Workerman\Worker))
#14 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(1082): Workerman\Worker::forkWorkers()
#15 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(433): Workerman\Worker::monitorWorkers()
#16 /home/vagrant/Code/dongiPal/components/Worker.php(17): Workerman\Worker::runAll()
#17 /home/vagrant/Code/dongiPal/commands/ChatController.php(152): app\components\Worker::runAll()
#18 [internal function]: app\commands\ChatController->actionIndex('start')
#19 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#21 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#22 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#23 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('chat', Array)
#24 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('chat', Array)
#25 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#26 /home/vagrant/Code/dongiPal/yii(20): yii\base\Application->run()
#27 {main}
Worker[2067] process terminated with exit()/die(). Please do not call exit()/die() in workerman.
worker[PHPSocketIO:2067] exit with status 256
```

code: 

```
$io = new SocketIO(2021);
$io->on('connection', function($socket)use($io){
$socket->addedUser = false;
});
Worker::runAll();
```

and for work with Yii2 framework, i Have write this method and use from this Worker: 
```
<?php
namespace app\components;

class Worker extends \Workerman\Worker{

    /**
     * @inheritdoc
     */
    public static function runAll()
    {
        global $argv;
        if ($argv[0] == 'yii' || $argv[0] == './yii') $argv = array_slice($argv, 1);
        if (isset($argv[2]) && $argv[2] == 'daemon') {
            $argv[2] = '-d';
        }

        parent::runAll();
    }
}
```

do you have any idea ? 
thanks for helping.
sorry for my bad language.

**Comment by walkor** [comment]
https://github.com/walkor/phpsocket.io/blob/master/src/Engine/Engine.php#L142
Can you show the codes of line 142 of src/Engine/Engine.php in your machine? 

> Stack trace:
> #0 [internal function]: PHPSocketIO\Engine\Engine->dealWebSocketConnect(NULL, true, Object(PHPSocketIO\Engine\Protocols\Http\Request))
> #1 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Engine.php(142): call_user_func(Array, NULL, true, Object(PHPSocketIO\Engine\Protocols\Http\Request))

I noticed that it should pass the 5 argument, but from the error that only four were passed.

And can you show your js codes?

**Comment by amin0256** [comment]
@walkor thank you for answering.
this code is like the source code: 
```
        if ($this->origins === "*:*" || empty($this->origins))
        {
            return call_user_func($fn, null, true, $req);
        }
```

there's not a special js code. I clone https://github.com/amritb/socketio-client-tool/ and connect to socket server.

**Comment by walkor** [comment]
Please update your phpsocket.io.

**Comment by amin0256** [comment]
@walkor phpsocket.io is updated.

```
➜  dongiPal git:(master) ✗ composer update
The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                                                   Nothing to install or update                                                                             
Generating autoload files
➜  dongiPal git:(master)
```

**Comment by amin0256** [comment]
@walkor I think this is not a question. Are you sure?

**Comment by walkor** [comment]
What label do you think it belongs to?

**Comment by amin0256** [comment]
@walkor I think every thing you pick is good :-D
How i can fix this error ?

**Comment by walkor** [comment]
I noticed @fly2xiang had added the fifth argument in this commit https://github.com/walkor/phpsocket.io/commit/6b1823c3293b77ddb97cf3f2c1c1c2b1e4074c4a on 28 Mar and which not released to composer.

I had release an new version(v1.1.5) 3 hours ago, please try to update again.

**Comment by amin0256** [comment]
thank you dear @walkor.

regards.
