### ISSUE TITLE
Workerman process terminated exit with status 65280 After 2-3 hours

### ISSUE THREAD

**Issue by prologictech** [walkor/phpsocket.io#236]
Hello there,

Till now i managed to keep my sockets working fine, and it is working fine in one of my project. but when i implemented same code in another project it work's fine but after some time the worker man process stops automatically.

when i checked workerman logs. it is giving me following log which says exit with status code 65280

```
2020-07-29 01:28:46 pid:30593 Worker[30593] process terminated
2020-07-29 01:28:46 pid:17956 worker[PHPSocketIO:30593] exit with status 65280
2020-07-29 03:57:53 pid:12635 Worker[12635] process terminated
2020-07-29 03:57:53 pid:17956 worker[PHPSocketIO:12635] exit with status 65280
2020-07-29 04:31:16 pid:12731 Worker[12731] process terminated
2020-07-29 04:31:16 pid:17956 worker[PHPSocketIO:12731] exit with status 65280
2020-07-29 04:38:40 pid:19620 Worker[19620] process terminated
2020-07-29 04:38:40 pid:17956 worker[PHPSocketIO:19620] exit with status 65280
2020-07-29 04:38:56 pid:20874 Worker[20874] process terminated
2020-07-29 04:38:56 pid:17956 worker[PHPSocketIO:20874] exit with status 65280
2020-07-29 04:43:13 pid:20875 Worker[20875] process terminated
2020-07-29 04:43:13 pid:17956 worker[PHPSocketIO:20875] exit with status 65280
2020-07-29 04:43:25 pid:21809 Worker[21809] process terminated
2020-07-29 04:43:25 pid:17956 worker[PHPSocketIO:21809] exit with status 65280
2020-07-29 04:43:36 pid:21811 Worker[21811] process terminated
2020-07-29 04:43:36 pid:17956 worker[PHPSocketIO:21811] exit with status 65280
2020-07-29 04:43:48 pid:21812 Worker[21812] process terminated
2020-07-29 04:43:48 pid:17956 worker[PHPSocketIO:21812] exit with status 65280
2020-07-29 04:43:51 pid:21838 Worker[21838] process terminated
2020-07-29 04:43:51 pid:17956 worker[PHPSocketIO:21838] exit with status 65280
2020-07-29 04:49:14 pid:21846 Worker[21846] process terminated
2020-07-29 04:49:14 pid:17956 worker[PHPSocketIO:21846] exit with status 65280
2020-07-29 04:50:00 pid:22882 Worker[22882] process terminated
2020-07-29 04:50:00 pid:17956 worker[PHPSocketIO:22882] exit with status 65280
2020-07-29 04:52:04 pid:22931 Worker[22931] process terminated
2020-07-29 04:52:04 pid:17956 worker[PHPSocketIO:22931] exit with status 65280
2020-07-29 05:00:52 pid:23606 Worker[23606] process terminated
2020-07-29 05:00:52 pid:17956 worker[PHPSocketIO:23606] exit with status 65280
```

i have contacted my sysadmin and he say's that he had already created this service as a system startup service it actually gets started automatically on server startup. The issue is it stops after 2-3 hours.

@walkor Please look into this and help me to solve this.

**Comment by walkor** [comment]
`exit with status 65280` means that your codes has fatal error.

**Comment by prologictech** [comment]
how to check at what place this fatal error occurs because i checked my apache error log but couldnot find any fatal error log there

**Comment by walkor** [comment]
1. Run command `php --ini` find your php.ini path for php cli.

2. Open php.ini find `error_log` and set a path to it for example '/tmp/php_error.log'.

3. Restart phpsocket.io.

4.

**Comment by ersunnyroy** [comment]
we are facing this issue..  
![image](https://user-images.githubusercontent.com/15190121/88909006-3d070480-d278-11ea-9b8e-f31ee9ac3aa2.png)

**Comment by prologictech** [comment]
Hello @walkor Thanks for your time

I tried your suggestion and my log file now is populated with following error

`
   [30-Jul-2020 11:01:33 UTC] PHP Fatal error:  Uncaught Exception in 
   /var/www/html/vendor/workerman/workerman/Worker.php:2235
   Stack trace:
   #0 /var/www/html/vendor/workerman/workerman/Worker.php(1524): Workerman\Worker->listen()
   #1 /var/www/html/vendor/workerman/workerman/Worker.php(1371): 
   Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
  #2 /var/www/html/vendor/workerman/workerman/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
  #3 /var/www/html/vendor/workerman/workerman/Worker.php(546): Workerman\Worker::forkWorkers()
  #4 /var/www/html/modules/my-message/message_live_chat.php(265): Workerman\Worker::runAll()
  #5 {main}
  thrown in /var/www/html/vendor/workerman/workerman/Worker.php on line 2235
  [30-Jul-2020 11:01:33 UTC] PHP Fatal error:  Uncaught Exception in 
  /var/www/html/vendor/workerman/workerman/Worker.php:2235
`


could you tell me what this issue is of? is it permission issue? if yes than  how can i resolve this issue? Is there anything i can do to manipulate code or it needs to be fixed by network admin

**Comment by walkor** [comment]
It looks like the port already in use by other program. Please use other port for your code.

**Comment by prologictech** [comment]
i checked my netstat and it is showing that workerman is using this port.

I tried to stop workerman and again checked netstat but it is still using that port, is it issue of server? or i did some terrible mistake?

I have attached Screen Shot for your reference. I am using port 3000 for socket connection

![image](https://user-images.githubusercontent.com/67745189/88919536-e229d900-d288-11ea-9fec-54635c774d04.png)

**Comment by walkor** [comment]
I can't tell you exactly why.
It may be that you have manually killed some processes, causing a process to remain.
Or forget that you started the service in another directory.
Or the program is deleted after the service is started, resulting in the process remaining.
Or start the program, but lose the PID file, so that the process can not stop, resulting in process residue.

Just kill all the phpsocket.io processes and start again.

**Comment by prologictech** [comment]
hey @walkor,

Thanks for your support and time,

according to your suggestion  I killed all process and started again my server, now the socket is starting but after some time it gets stop again

when i checked my error_log file it is giving me this below error

`[04-Aug-2020 04:15:04 UTC] PHP Warning:  Error while sending STMT_PREPARE packet. PID=26815 in /var/www/html/classes/class.db.php on line 766
[04-Aug-2020 04:15:04 UTC] PHP Fatal error:  Problem preparing query (INSERT INTO `table_name`(`chat_id`, `sender_id`, `message`, `message_type`, `is_read`, `file`,`file_type`, `created_at`) VALUES ('5', '40', 'adsfadsf', 'T', '0', '', '', '2020-08-04 04:15:03')) MySQL server has gone away in /var/www/html/classes/class.db.php on line 767`

What could be causing this? because when i fire this query in myadmin it works fine so clearly query has no issue.

**Comment by LuckyCyborg** [comment]
This error happens because a MySQL connection is not permanent, but it is closed by server after some time, depending in its configuration.

Many do not hit this problem while using a PHP site, because a new SQL connection is open and closed every time the site responds to a request (i.e. serve a page to a visitor) but for console scripts which runs for very long term - like is Workerman, thins could be an real problem.

The usual solution is to encapsulate the MySQL connect in a "smart" API which is able to detect the server link lossing and reconnect. As an example, about how can be done for Workerman, you can take a look there:

https://github.com/nova-framework/quasar/blob/master/system/Database/Connection.php

Nova's Quasar is a Pusher like server, made on top of PHPSockerIO - hence also on top Workerman.
