### ISSUE TITLE
Workerman\Lib\Timer not found

### ISSUE THREAD

**Issue by binemmanuel** [walkor/phpsocket.io#281]
Error: Class "Workerman\Lib\Timer" not found in /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/phpsocket.io/src/Engine/Socket.php:238
Stack trace:
#0 [internal function]: PHPSocketIO\Engine\Socket->onClose()
#1 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/phpsocket.io/src/Event/Emitter.php(93): call_user_func_array(Array, Array)
#2 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/phpsocket.io/src/Engine/Transport.php(68): PHPSocketIO\Event\Emitter->emit('close')
#3 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/workerman/src/Connection/TcpConnection.php(944): PHPSocketIO\Engine\Transport->onClose(Object(Workerman\Connection\TcpConnection))
#4 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/workerman/src/Connection/TcpConnection.php(592): Workerman\Connection\TcpConnection->destroy()
#5 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/workerman/src/Events/Select.php(352): Workerman\Connection\TcpConnection->baseRead(Resource id #70)
#6 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/workerman/src/Worker.php(2399): Workerman\Events\Select->run()
#7 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/workerman/src/Worker.php(1524): Workerman\Worker->run()
#8 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/workerman/src/Worker.php(1371): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#9 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/workerman/src/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
#10 /Users/binemmanuel/Projects/zerabtech_app/backend/vendor/workerman/workerman/src/Worker.php(557): Workerman\Worker::forkWorkers()
#11 /Users/binemmanuel/Projects/zerabtech_app/backend/src/socket.php(14): Workerman\Worker::runAll()
#12 {main}
worker[PHPSocketIO:55411] exit with status 64000

**phpsocket.io Version**
`workerman/phpsocket.io": "^1.1.14`

**Comment by walkor** [comment]
Please upgrade workerman/phpsocket.io to 1.1.15

**Comment by mnaz-trustanalytica** [comment]
@walkor because of this change, you broke the package.
here, I am getting error
![image](https://user-images.githubusercontent.com/115188110/204607257-a1b18737-d33b-44cb-9799-0ef7bd5c74f3.png)

**Comment by marcosmarcolin** [comment]
Closed due to inactivity or open for too long.

If you still need support, please open a new issue.
