### ISSUE TITLE
ErrorException: Declaration of PHPSocketIO\Socket::emit($ev) should be compatible with PHPSocketIO\Event\Emitter::emit($event_name = NULL) 

### ISSUE THREAD

**Issue by awh521** [walkor/phpsocket.io#58]
ErrorException: Declaration of PHPSocketIO\Socket::emit($ev) should be compatible with PHPSocketIO\Event\Emitter::emit($event_name = NULL) in /Users/admin/Server/www/bandari/php-project/vendor/workerman/phpsocket.io/src/Socket.php:460
Stack trace:
#0 /Users/admin/Server/www/bandari/php-project/vendor/composer/ClassLoader.php(414): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Declaration of ...', '/Users/admin/Se...', 460, Array)
#1 /Users/admin/Server/www/bandari/php-project/vendor/composer/ClassLoader.php(414): include()
#2 /Users/admin/Server/www/bandari/php-project/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/Users/admin/Se...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('PHPSocketIO\\Soc...')
#4 /Users/admin/Server/www/bandari/php-project/vendor/workerman/phpsocket.io/src/Nsp.php(60): spl_autoload_call('PHPSocketIO\\Soc...')
#5 /Users/admin/Server/www/bandari/php-project/vendor/workerman/phpsocket.io/src/Client.php(64): PHPSocketIO\Nsp->add(Object(PHPSocketIO\Client), Object(PHPSocketIO\Nsp), Array)
#6 /Users/admin/Server/www/bandari/php-project/vendor/workerman/phpsocket.io/src/SocketIO.php(100): PHPSocketIO\Client->connect('/')
#7 [internal function]: PHPSocketIO\SocketIO->onConnection(Object(PHPSocketIO\Engine\Socket))
#8 /Users/admin/Server/www/bandari/php-project/vendor/workerman/phpsocket.io/src/Event/Emitter.php(92): call_user_func_array(Array, Array)

新版本1.0.9有问题,换1.0.8就没有问题

**Comment by awh521** [comment]
if you have problem,I suggest use version 1.0.1.
